name: Build TabList

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build (skip Bungee)
        run: ./gradlew clean build \
             -x :bungee:compileJava \
             -x :bungee:processResources \
             -x :bungee:jar \
             -x :bungee:build

      - name: Upload Bukkit jar
        uses: actions/upload-artifact@v4
        with:
          name: TabList-5.7.8-SNAPSHOT.jar
          path: bukkit/build/libs/TabList-bukkit*.jar
